postgres:
  host: daten
  port: 5432
  user: hello_django
  password: hello_django
  db_name: herredb

auth:
  activation_days: {{cookiecutter.herre.activation_days}}
  token_expire_seconds:  {{cookiecutter.herre.token_expire_seconds}}

server:
  debug: {{cookiecutter.herre.debug}}
  hosts:
    {% for host in cookiecutter.herre.hosts%}- "{{host}}"
    {% endfor %}

scopes:
  read: "Reading all of your Data"
  read_starred: "Reading all of your shared Data"
  provider: "Can act as a provider"
  introspection: "Introspect the Token scope"
  can_provide: "Can Provide Nodes"
  can_assign: "Can Assign Nodes"
  can_template: "Can Template Nodes"
  can_create: "Can Create Nodes"
  can_forward_bounce: "Can reserve and assign to Nodes mimicking other Users (only backend and admin)"
  can_create_identifier: "Can create new identifier for the platform"

security:
  admins:
    - username: demo
      password: demodemo
      email: demo@demo.com
      groups:
        - admin
        - phd

  loks:
    - username: jhnnsrs
      password: johannesroos
      email: johannes.roos@u-bordeaux.fr
      groups:
        - sibaritateam
        - nagerlteam
        - admin
        - phd
    - username: tom
      password: tomtomtom
      email: tom.delaire@u-bordeaux.fr
      groups:
        - sibaritateam
        - phd
        - developer
    - username: ihsanne
      password: ihsanneihsanne
      email: ihsanne.idrissi@u-bordeaux.fr
      groups:
        - sibaritateam
        - phd
    - username: agata
      password: agataagata
      email: agata.idziak@u-bordeaux.fr
      groups:
        - nagerlteam
        - phd

  secret_key: 9=9u7c35!*p_h674kv*t^8ntefnf*#)z_h%6$sdfoisnepuifonspoinef#b(oe=_mwysw+
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAvIrkAA1Tr8pLRR08xXEszuyi/+QGRQ3J7o5j7B+HJLv2MWpp
    d+fgoPQYc9nOkZcA9Jizsvm0bqcXe/8zdxaUz7bA+nq3hxLolO4q4SXRxNuBIcNr
    fLizFrWku5csO9ZfS4EXQGOGAWsVE1WbSRBCgAcOR8eq8gB0ai4UByB/xGlwobz1
    bkuXd3jGVN2oeCo7gbij/JaMrOSkh9wX/WqZlbrEWEFfgURENACn45Hm4ojjLepw
    /b2j7ZrHMQxvY1THi6lZ6bp9NdfkzyE6JhZbSVOzd/dHy+gLBx2UuvmovVEhhxzw
    RJYtPdqlOWuUOjO24AlpPv7j+BSY7eGSzYU5oQIDAQABAoIBAALJpu9dQxSBUDWY
    ZhKhRsFUfGB+NZ2Fw6uUTWPrX2sqoExAv4h3VDntAgOMf+JlMi1rqJSH3qQYMl+x
    +UfUfKTJlfbeI6KKpAe3scicb4qSmEkwg4FXlcZLL0Fazdugos4R/Y8FKbERrUEY
    7e/ZnrIX6J0lFaD4YsBDKCam01zLD9EW+2e565+KwjK8Cqf10UyzCPYSF9OcYCD3
    bczX01pC2yugUgQHrALleT1L1ZQt2ioMlaAksfUr7AcVAq06J3N1rwwCr9dOQ3bM
    3sRWzEaPD0G6S1ZpwZ3k4ns8lfl1Gw6SaAXMkVEC4Ti+JRG4MOlYYOsAGx1mc68u
    VQQXvrUCgYEA29gfZ54Ft9YApQRBpWC6xiGT1Uj+dcznpPuPmcJNljtLdz1Bsib7
    FepMyGqBPhRogZ0hYlc5EcpAxqh9MjaQJ+hD2hM+22gchRwjOBtk8nhmSLMlJzZX
    XeiwKdVpmifmXEaVP92HB9HGkIF41KKqfeoqqJjKWOnmCORRPYDrCcMCgYEA24zn
    qRoo/AqEFlpSMyxyCCDp+5X9kL6lnsOhn7YPfNuRiCgUHUbRfexQxA7XXPqpJAkO
    46jPkvdDfklod3+BE3SZaTLBatqmTKkg/tDzS2WT58luPwsa1vQGSMi/ji0KeDGc
    7m7UM4kWZakOibupSXZ0Nuf7cp3AX4X+LyTF1MsCgYEAtffwFq5AAWiLZAtf4ulr
    76+/U911ckBGxNLMi/K+kclGr83uYO3PCtbC82jkzWPLFO3gwit8O3Nzpnu0FSoA
    rGeeMhWYA7frU2p05G4YYnKyBx7xc8GRE1QU7KuPG2BHVr29r/1HVXuXpejlAOwb
    vtlisea2Jl6EX3vMmuHoqk0CgYACS3W8ab6V69I3nZgQWt2SQi3P6GBvG98FSsws
    rC17Q5xAzRJwv+W+qDKr6e/MU/5ilwmlzYTl51m4PzItVZLWzjgwRkyJPmHQmU/z
    +eEhH52tJYjWddpA9un95sNBzCy41uPqBhSHuV4Xj+3L+L8rOma6kDAroYR6Ox9O
    BNdggwKBgBxEvmWswlE8r3Ej8tUb80v29jjh1tzDba/fL4xaN0ZMlnh1aa6KLubp
    V57aaQpu670EOYxZi/TBdPZJDu4u6xPjRYnmplicoQKtLF9ZsA8g93Q233lXrhWb
    2N46/mnTS3/Ck1u8MJDuJlJWPnUEZCRIWoVZpnc8tC6YwQ3s1JWj
    -----END RSA PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIrkAA1Tr8pLRR08xXEs
    zuyi/+QGRQ3J7o5j7B+HJLv2MWppd+fgoPQYc9nOkZcA9Jizsvm0bqcXe/8zdxaU
    z7bA+nq3hxLolO4q4SXRxNuBIcNrfLizFrWku5csO9ZfS4EXQGOGAWsVE1WbSRBC
    gAcOR8eq8gB0ai4UByB/xGlwobz1bkuXd3jGVN2oeCo7gbij/JaMrOSkh9wX/WqZ
    lbrEWEFfgURENACn45Hm4ojjLepw/b2j7ZrHMQxvY1THi6lZ6bp9NdfkzyE6JhZb
    SVOzd/dHy+gLBx2UuvmovVEhhxzwRJYtPdqlOWuUOjO24AlpPv7j+BSY7eGSzYU5
    oQIDAQAB
    -----END PUBLIC KEY-----
  key_type: RS256
  issuer: herre

apps:
  - name: Tests
    client_id: DSNwVKbSmvKuIUln36FmpWNVE2KrbS2oRX0ke8PJ
    client_secret: Gp3VldiWUmHgKkIxZjL2aEjVmNwnSyIGHWbQJo6bWMDoIUlBqvUyoGWUWAe6jI3KRXDOsD13gkYVCZR0po1BLFO9QT4lktKODHDs0GyyJEzmIjkpEOItfdCC4zIa3Qzu
    client_type: public
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Port
    client_id: 7JbA1yi2iQuqc6b4BUjtcYLBOB92V6fQfaE87EFF
    client_secret: 699FBMqg32oRcwQ4m06R8m5j1AWIoXiDnJ2UqEpAEtNoegtpmk69Wg3zD8Hk3C8pKws6QHzEhuuIU14LmUHq2qM12Pze37atxTslAnrOPBGv3PEKjKGMvcSguRW1JGZ6
    client_type: confidential
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Elements
    client_id: AoNMdwnUGwULwi0UVOD04wpoDjsmX8i8BniBRarF
    client_secret: ke9LXivKkZSyi57eLWFGozHtXH66JUjhJZOisTuxNf0vBo5QcAQAUwHyzYQZgRKlaPNuQNZlxsQbTus1ruThhocOGs4TFg4L2KtXcqwGVRsWWb4k9CEzHt7R3UADjNgW
    client_type: confidential
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Fluss
    client_id: nX1RcMSQ3FkQWCuw127B1TwZTpxyl7jloDP8GscC
    client_secret: YdZFYHU2nNn88qPxkqPHqAmiFcznnZBrLCr9iIPjcPtnZ2hjN54Ws0grbxefYf0nsbmImcTHtVgLmzlEnjJJWvchjBq9JRpWFNBvpDKF8WHjZPnsL9Dna3R9Ccfxr9Of
    client_type: confidential
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Gucker
    client_id: X2Duxlt4u1XrvrWQQM4qn2mWoud8407Ya1FTVJ1Z
    client_secret: PmULWW7kDGoOUVs6ILg8eOHdJwEpyDuVGRuig96oAs1ki7wj1J6daK3yXGd1HOJJ1wgyZkf7UlujgG9Z8VQhYSbMCnsALUlHmYZhpvm8wVFuUQeqdQQUzhJe1bL2hwnC
    client_type: confidential
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Generic
    client_id: 2IInJHMgz4SDwsGpdGZvYDsoa2FAGti5hVzANwlE
    client_secret: WQu6bU9LXGwaM5RnAPouEqvvVlJo8pf67sQGR5iZbgCM3to7ggYMcIwxEAP92GTlIHcwzDYgo2OIJcSLpQKqZrWutldWso0zEFAVnUhixYR2UYEVo1iEZ86qBLXo0ASS
    client_type: confidential
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Stardist
    client_id: x3iAKZr3ZQTSIEUw8ZVyOcck9OCXbPBCXhpZe8gL
    client_secret: SxuZCGCPeQ9fDN1RnB5i7QwHxbq0k71ALCwBDzxFiOAJXuuFvw1funAPlpOm3KNsytTg8v9OvXcBCA75zVVyx9DXAhQdxqUsJzvcBasvi8474W8QO4Gws2Y5UkJF0dOW
    client_type: confidential
    tenant: demo@demo.com
    grant_type: client-credentials
    redirect_uris: []
  - name: Wasser
    client_id: PsdU71PlUYeC4hP4aDf8pTdm2Hv9xYKdrxCFI5RO
    client_secret: 8jXSNhrH7fllN8cGjxg7y2Jl1INb22wlDSmUBepb9aRDGV3al5pfNzswS85MPEvpN5vnfrPkrIERQ6kcMHLiISr4HcYirivdtrnyMjFMlzKGvlCrwfkNJmtQgCLZmH4X
    client_type: public
    tenant: demo@demo.com
    grant_type: authorization-code
    redirect_uris:
      - http://localhost:6789/callback
      - http://p-tnagerl-lab1:8040/hub/oauth_callback
      - com.example.feuer:/callback
      - http://localhost:3000
      - http://localhost
      - http://p-tnagerl-lab1:3000
      - http://p-tnagerl-lab1
      - http://100.108.99.108:3000
      - http://100.108.99.108:3000
      - http://100.108.99.108
      - https://arkitekt-mutter.netlify.app
  - name: MikroJ
    client_id: hmtwKgUO092bYBOvHngL5HVikS2q5aWbS7V1ofdU
    client_secret: V0RqJveg5391edG9EQ30n8JqQev1GI1CxhbHYMG6oJer5nxllpwPyjy9yfETemESzrysPUnqwAVAJSa0wHv2AdrUFGOzjwR2kBrscIHWrVRRYK4soFBYY4rTujpWiyWP
    client_type: public
    tenant: demo@demo.com
    grant_type: authorization-code
    redirect_uris:
      - http://localhost:3000/callback
      - http://p-tnagerl-lab1:8040/hub/oauth_callback
      - com.example.feuer:/callback
      - http://localhost:6767/
      - http://p-tnagerl-lab1:3000
      - http://100.108.99.108:3000
      - http://100.108.99.108:3000
      - https://arkitekt-mutter.netlify.app
  - name: Felix Denoise
    client_id: Zvc8fwLMMINjcAxoaTBG2L6ATlV746D3Zc4T4Wiu
    client_secret: bPDJKpvrZkhqsIvytwJuuLv8SEKeybPaPeMVpIRtdByLUERtyES2v18Dm38PUbVO0myUFAwLzwyWjo4jk91Yrhlfn51DPXN7MxYCIRedXSaNabvINv8EKv3kcWSY8Wos
    client_type: public
    tenant: demo@demo.com
    grant_type: authorization-code
    redirect_uris:
      - http://localhost:6767/
  - name: Napari
    client_id: go8CAE78FDf4eLsOSk4wkR4usYbsamcq0yTYqBiY
    client_secret: oO4eJgvv41Nkr9EaNAmZ5YI4WGgfJznUMW5ReGIcI6NsSXZiud3w3y2yGxdMf2WhEMdUKD6MMalLv1rlM8d6h5Q6vJR9vLbaKSHj2V5RpDrNVUWnJ1s2OmxiPSR6qoNH
    client_type: public
    tenant: demo@demo.com
    grant_type: authorization-code
    redirect_uris:
      - http://localhost:3000/callback
      - http://p-tnagerl-lab1:8040/hub/oauth_callback
      - com.example.feuer:/callback
      - http://localhost:6767/
      - http://p-tnagerl-lab1:3000
      - http://100.108.99.108:3000
      - http://100.108.99.108:3000
      - https://arkitekt-mutter.netlify.app
  - name: Hub
    client_id: xLhetkip7HUziKzeVgDIRo5AwSVHKS66dkbkeEhz
    client_secret: tQixSdcYAEwtcZzRO7jGMMz682YpRC9lmd9AW5wU5j6nEZmvinvwpoj9lTEJ9MkYpCKYax39C1NjqwxvAA5zPvzu56nqhJPnKAGoVR1X43fVTEGa52JzNt1TjNY8kHo9
    client_type: public
    tenant: demo@demo.com
    grant_type: authorization-code
    redirect_uris:
      - http://localhost:3000/callback
      - http://p-tnagerl-lab1:8040/hub/oauth_callback
      - com.example.feuer:/callback
      - http://localhost:6767/
      - http://p-tnagerl-lab1:3000
      - http://100.108.99.108:3000
      - http://100.108.99.108:3000
      - https://arkitekt-mutter.netlify.app
  - name: Fakts
    client_id: UGqhHa2OS8NmTRjkVg8WKOWczYqkDVuK61yCueuO
    client_secret: 3oosB6FoC2iGASI8tkN16S8mPtlIvhqetvG5EOOJcLkn3txggTRxdp35G23CkNmvEY6fQXIXHaSzTa9Jb5Rk1hxWx0Fey0iUeOv2ZN568Z9z14kUbUbm4QQ1nacUW1gD
    client_type: public
    tenant: demo@demo.com
    grant_type: authorization-code
    redirect_uris:
      - http://localhost:3000/api/auth/callback/herre
      - http://localhost:3000/api/auth/callback/herre/
      - http://p-tnagerl-lab1:8040/hub/oauth_callback
      - com.example.feuer:/callback
      - http://localhost:6767/
      - http://p-tnagerl-lab1:3000
      - http://100.108.99.108:3000
      - http://100.108.99.108:3000
      - https://arkitekt-mutter.netlify.app